import type { ProductAnalyticsRecord } from "./analytics";

// Custom environment variable declarations that augment the auto-generated Cloudflare.Env.
// (worker-configuration.d.ts is auto-generated by `wrangler types` and should not be edited.)

declare global {
  namespace Cloudflare {
    interface Env {
      // Deployment-wide admins, identified by verified principal "<issuer>:<subject>" — e.g.
      // "password:admin" for a password account, or "<provider issuer>:<provider subject>" for an
      // OAuth sign-in. Never an email or other mutable profile attribute.
      ADMINS?: string[];

      // Workers AI binding (injected by generate-wrangler-prod / run-dev-server; not in base wrangler.jsonc).
      WORKERS_AI: Ai;

      // AI Gateway mode: when CF_AI_GATEWAY is set, supported providers are routed through
      // Cloudflare AI Gateway with server-managed keys. Users don't need their own keys.
      // Inference goes over HTTPS with tokens (there is no Workers-binding transport), so the
      // ACCOUNT_ID/API_TOKEN pair is REQUIRED whenever CF_AI_GATEWAY is set.
      CF_AI_GATEWAY?: string;            // Gateway name (enables gateway mode)
      CF_AI_GATEWAY_PROVIDERS?: string;   // Comma-separated list: "anthropic,openai,google,cloudflare"
      CF_AI_GATEWAY_ACCOUNT_ID?: string;  // Gateway owner account ID (required with CF_AI_GATEWAY)
      CF_AI_GATEWAY_API_TOKEN?: string;   // Run + Read token for inference and cost-log reads
      CF_AI_GATEWAY_WAI?: string;         // Optional Workers AI gateway override
      CF_AI_GATEWAY_WAI_DIRECT?: string;  // "true" to route Workers AI to its plain REST endpoint
                                          // (no gateway, no cost logs) instead of a named Gateway
      // Note: outside gateway mode, Workers AI (provider "cloudflare") is BYOK like every other
      // provider -- the account ID and API token live in the user's model config, not in env.

      // Deployment-managed providers are available to every user without exposing the backing
      // credential through RPC or per-user model storage. OpenRouter currently owns this direct
      // provider path; Cloudflare AI Gateway providers remain configured through CF_AI_GATEWAY_*.
      DEPLOYMENT_AI_PROVIDERS?: string;     // Comma-separated list; currently supports "openrouter"
      DEPLOYMENT_AI_DEFAULT_MODEL?: string; // Suggested model ID placed first in model lists
      OPENROUTER_API_TOKEN?: string;        // Backend-only Worker secret

      // E2B control-plane credential for thread orbs (sandboxes). Backend-only Worker secret;
      // never forwarded to sandboxes, agents, or the frontend. Absent = orbs disabled.
      E2B_API_KEY?: string;

      // Signing key for orb-facing tokens (turn inference grants). Backend-only Worker secret.
      // A sandbox holds only tokens signed by this key -- never a provider credential. Absent =
      // the orb inference proxy refuses every request.
      ORB_TOKEN_SIGNING_KEY?: string;

      // Template storage bindings.
      TEMPLATES: KVNamespace;             // Workers KV for template metadata lookup
      TEMPLATE_CONTENT: R2Bucket;         // R2 bucket for template code snapshots

      // User avatar storage.
      AVATARS: KVNamespace;                // Workers KV for user avatar images

      // Note: gatekeeper service bindings (GATEKEEPER_*) are intentionally NOT declared here. Core
      // discovers them generically by scanning env for the GATEKEEPER_ prefix (buildGatekeeperVendorMap)
      // and never references a specific gatekeeper by name, so naming one here would be wrong.

      // Optional product analytics stream. Deployments can bind this to a
      // structured Cloudflare Pipelines stream; local/dev configs omit it and analytics no-op.
      PRODUCT_ANALYTICS?: import("cloudflare:pipelines").Pipeline<ProductAnalyticsRecord>;

      // Optional browser error pipeline. Both bindings must be present before reports dispatch.
      FRONTEND_ERROR_REPORTER?: Service<
        import("@gadgets/backend-utils/error-reporting").ErrorReporter
      >;
      FRONTEND_ERROR_RATE_LIMITER?: RateLimit;

      // The Browser Run binding (BROWSER) used to render Gadget exports is intentionally NOT
      // redeclared here: wrangler's generated types make it required, and TypeScript 7 rejects
      // weakening it to optional in a merged augmentation. Self-hosted deployments may omit the
      // binding, so use sites read it as `BrowserRun | undefined` and null-check.

      // ---------------------------------------------------------------------------------------------
      // Optional features: sign-in via authentication gatekeepers + AI Gateway billing (free-tier
      // limits / top-up). All OFF by default; existing password / Cloudflare Access deployments are
      // unaffected. OAuth app credentials live on the gatekeeper Workers, not here.
      // ---------------------------------------------------------------------------------------------

      // Cloudflare Access configuration. When CF_ACCESS_AUD is set, the deployment authenticates via
      // Cloudflare Access (SSO). (Also referenced via a local Env extension in server.ts.)
      CF_ACCESS_AUD?: string;   // audience
      CF_ACCESS_ISS?: string;   // team URL, e.g. https://<team>.cloudflareaccess.com

      // Comma-separated allowlist of gatekeeper vendor ids permitted to drive sign-in (e.g.
      // "google,github,cloudflare"). A listed gatekeeper must also advertise providesAuth. Empty =
      // no gatekeeper sign-in (password / CF Access only).
      AUTH_GATEKEEPERS?: string;

      // Set to "true" to disable username/password login + signup (gatekeeper sign-in only). Only
      // takes effect when at least one auth gatekeeper is allowlisted (otherwise password auth stays
      // on to avoid locking everyone out).
      DISABLE_PASSWORD_AUTH?: string;

      // Enables the Cloudflare free-tier limits + top-up flow when set to "true".
      ENABLE_CLOUDFLARE_LIMITS?: string;

      // Public base URL of the deployment.
      PUBLIC_BASE_URL?: string;

      // Daily free-tier LLM-call limit (per user). Defaults to DEFAULT_DAILY_LLM_CALL_LIMIT.
      DAILY_LLM_CALL_LIMIT?: string;

      // Minimum connected-account balance (USD) to proceed via BYOK. Defaults to
      // MINIMUM_CLOUDFLARE_BALANCE.
      MINIMUM_CLOUDFLARE_BALANCE?: string;
    }
  }
}
