/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedContextRouteImport } from './routes/_authenticated/context'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedEmailRouteImport } from './routes/_authenticated/email'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedGatekeepersRouteImport } from './routes/_authenticated/gatekeepers'
import { Route as AuthenticatedOutputsRouteImport } from './routes/_authenticated/outputs'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProvidersRouteImport } from './routes/_authenticated/providers'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedThreadsRouteImport } from './routes/_authenticated/threads'
import { Route as GadgetIdRouteImport } from './routes/gadget.$id'
import { Route as TemplateIdRouteImport } from './routes/template.$id'
import { Route as AuthenticatedGatekeepersAppIdRouteImport } from './routes/_authenticated/gatekeepers_.$appId'
import { Route as AuthenticatedThreadIdRouteImport } from './routes/_authenticated/thread.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContextRoute = AuthenticatedContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmailRoute = AuthenticatedEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGatekeepersRoute =
  AuthenticatedGatekeepersRouteImport.update({
    id: '/gatekeepers',
    path: '/gatekeepers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOutputsRoute = AuthenticatedOutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProvidersRoute = AuthenticatedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedThreadsRoute = AuthenticatedThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const GadgetIdRoute = GadgetIdRouteImport.update({
  id: '/gadget/$id',
  path: '/gadget/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateIdRoute = TemplateIdRouteImport.update({
  id: '/template/$id',
  path: '/template/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGatekeepersAppIdRoute =
  AuthenticatedGatekeepersAppIdRouteImport.update({
    id: '/gatekeepers_/$appId',
    path: '/gatekeepers/$appId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedThreadIdRoute = AuthenticatedThreadIdRouteImport.update({
  id: '/thread/$id',
  path: '/thread/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/context': typeof AuthenticatedContextRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/email': typeof AuthenticatedEmailRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/gatekeepers': typeof AuthenticatedGatekeepersRoute
  '/outputs': typeof AuthenticatedOutputsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/threads': typeof AuthenticatedThreadsRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/template/$id': typeof TemplateIdRoute
  '/gatekeepers/$appId': typeof AuthenticatedGatekeepersAppIdRoute
  '/thread/$id': typeof AuthenticatedThreadIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/context': typeof AuthenticatedContextRoute
  '/conversations': typeof AuthenticatedConversationsRoute
  '/email': typeof AuthenticatedEmailRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/gatekeepers': typeof AuthenticatedGatekeepersRoute
  '/outputs': typeof AuthenticatedOutputsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/threads': typeof AuthenticatedThreadsRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/template/$id': typeof TemplateIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/gatekeepers/$appId': typeof AuthenticatedGatekeepersAppIdRoute
  '/thread/$id': typeof AuthenticatedThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/context': typeof AuthenticatedContextRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRoute
  '/_authenticated/email': typeof AuthenticatedEmailRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/gatekeepers': typeof AuthenticatedGatekeepersRoute
  '/_authenticated/outputs': typeof AuthenticatedOutputsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/providers': typeof AuthenticatedProvidersRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/threads': typeof AuthenticatedThreadsRoute
  '/gadget/$id': typeof GadgetIdRoute
  '/template/$id': typeof TemplateIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/gatekeepers_/$appId': typeof AuthenticatedGatekeepersAppIdRoute
  '/_authenticated/thread/$id': typeof AuthenticatedThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/calendar'
    | '/channels'
    | '/context'
    | '/conversations'
    | '/email'
    | '/explore'
    | '/gatekeepers'
    | '/outputs'
    | '/profile'
    | '/providers'
    | '/templates'
    | '/threads'
    | '/gadget/$id'
    | '/template/$id'
    | '/gatekeepers/$appId'
    | '/thread/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/admin'
    | '/calendar'
    | '/channels'
    | '/context'
    | '/conversations'
    | '/email'
    | '/explore'
    | '/gatekeepers'
    | '/outputs'
    | '/profile'
    | '/providers'
    | '/templates'
    | '/threads'
    | '/gadget/$id'
    | '/template/$id'
    | '/'
    | '/gatekeepers/$appId'
    | '/thread/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/calendar'
    | '/_authenticated/channels'
    | '/_authenticated/context'
    | '/_authenticated/conversations'
    | '/_authenticated/email'
    | '/_authenticated/explore'
    | '/_authenticated/gatekeepers'
    | '/_authenticated/outputs'
    | '/_authenticated/profile'
    | '/_authenticated/providers'
    | '/_authenticated/templates'
    | '/_authenticated/threads'
    | '/gadget/$id'
    | '/template/$id'
    | '/_authenticated/'
    | '/_authenticated/gatekeepers_/$appId'
    | '/_authenticated/thread/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  GadgetIdRoute: typeof GadgetIdRoute
  TemplateIdRoute: typeof TemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/context': {
      id: '/_authenticated/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof AuthenticatedContextRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email': {
      id: '/_authenticated/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AuthenticatedEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gatekeepers': {
      id: '/_authenticated/gatekeepers'
      path: '/gatekeepers'
      fullPath: '/gatekeepers'
      preLoaderRoute: typeof AuthenticatedGatekeepersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outputs': {
      id: '/_authenticated/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof AuthenticatedOutputsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/providers': {
      id: '/_authenticated/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/threads': {
      id: '/_authenticated/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof AuthenticatedThreadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/gadget/$id': {
      id: '/gadget/$id'
      path: '/gadget/$id'
      fullPath: '/gadget/$id'
      preLoaderRoute: typeof GadgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$id': {
      id: '/template/$id'
      path: '/template/$id'
      fullPath: '/template/$id'
      preLoaderRoute: typeof TemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gatekeepers_/$appId': {
      id: '/_authenticated/gatekeepers_/$appId'
      path: '/gatekeepers/$appId'
      fullPath: '/gatekeepers/$appId'
      preLoaderRoute: typeof AuthenticatedGatekeepersAppIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/thread/$id': {
      id: '/_authenticated/thread/$id'
      path: '/thread/$id'
      fullPath: '/thread/$id'
      preLoaderRoute: typeof AuthenticatedThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedContextRoute: typeof AuthenticatedContextRoute
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRoute
  AuthenticatedEmailRoute: typeof AuthenticatedEmailRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedGatekeepersRoute: typeof AuthenticatedGatekeepersRoute
  AuthenticatedOutputsRoute: typeof AuthenticatedOutputsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProvidersRoute: typeof AuthenticatedProvidersRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedThreadsRoute: typeof AuthenticatedThreadsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGatekeepersAppIdRoute: typeof AuthenticatedGatekeepersAppIdRoute
  AuthenticatedThreadIdRoute: typeof AuthenticatedThreadIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedContextRoute: AuthenticatedContextRoute,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRoute,
  AuthenticatedEmailRoute: AuthenticatedEmailRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedGatekeepersRoute: AuthenticatedGatekeepersRoute,
  AuthenticatedOutputsRoute: AuthenticatedOutputsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProvidersRoute: AuthenticatedProvidersRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedThreadsRoute: AuthenticatedThreadsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGatekeepersAppIdRoute: AuthenticatedGatekeepersAppIdRoute,
  AuthenticatedThreadIdRoute: AuthenticatedThreadIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  GadgetIdRoute: GadgetIdRoute,
  TemplateIdRoute: TemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
